# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a3b41d4b17456b0c5143485d28956e25016fa6ededb35bd0965c5433f29bef0098853b0c3fdc02c597968fb8cc4683b7e0ed497b5f22aa5fde821deb0d73565

test:
  secret_key_base: 5ad909cf89b1fee190053d7cc007a38ae99a9ac98fa3dd23f12d84742de99ef055e902f2c340353f56ce1d40769c3328134b82a6a5d1ec695375d8de76feb798

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
